version: 0.2
phases:
  build:
    commands:
      - echo "hello"
      - echo "we're building"
      - ls
      - echo "after ls"
      - zip -r lambda.zip lambda
      - s3 cp lambda.zip s3://my-test-code-bucket1/