version: 0.2
phases:
  build:
    commands:
      - echo "hello"
      - echo "we're building"
      - ls
      - echo "after ls"
      - zip -r lambda.zip lambda
      - aws s3 cp --debug "lambda.zip" "s3://my-test-code-bucket1/"
      - touch myJson.json
      - echo "{'foo':'bar'}" > myJson.json
artifacts:
  files:
    - 'lambda.zip'