version 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - echo hello world from install
  pre_build:
    commands:
      - echo In PreBuild
      - npm install
  build:
    commands:
      - echo starting build

